### ISSUE TITLE
`vagrant provision` is unable to execute

### ISSUE THREAD

**Issue by valerie-roske** [Microwave-MVC/microwave-rails-chef#10]
When making changes to the Vagrantfile, running `vagrant provision` exits unsuccessfully with the following message:

```
/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- chef/application/solo (LoadError)
    from /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/bin/chef-solo:22:in `<main>'
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

Running `vagrant destroy && vagrant up` works, though. Investigate why `vagrant provision` isn't cooperating with Chef.

**Comment by valerie-roske** [comment]
Looks like it was a vagrant problem. :) Solved by upgrading vagrant from 1.5.3 to 1.7.2, so I'm closing this issue.
